import createClient, { type Middleware } from "openapi-fetch";

import type { components, paths } from "./schema";

/**
 * The backend, typed from its own OpenAPI document.
 *
 * `schema.d.ts` is generated by `npm run api` and committed. That makes the contract a
 * reviewable file rather than a build-time fetch: a route whose shape changed shows up
 * as a diff, and CI fails if the committed schema and the application disagree — the
 * same arrangement `apps/bot/tests/test_contract.py` gives the bot.
 *
 * Two things are not in the schema on purpose. `/auth/login` and `/auth/callback` are
 * places a browser *navigates*, not calls, so they are `include_in_schema=False` and
 * appear here as plain URLs.
 */

export const LOGIN_URL = "/api/auth/login";

/**
 * Everything shares one origin, so the session cookie needs no cross-site handling.
 *
 * Absolute rather than the bare `/api` it resolves to: `fetch` outside a browser will
 * not resolve a relative URL, and the tests run the real client under jsdom against a
 * real HTTP interceptor. Anchoring it to the page's own origin is the same request
 * either way.
 */
const pageOrigin = typeof location === "undefined" ? undefined : location.origin;
const BASE_URL = new URL("/api", pageOrigin ?? "http://localhost").href;

/** What the backend says when it refuses. */
export interface Problem {
  detail?: unknown;
}

export class ApiError extends Error {
  readonly status: number;

  constructor(status: number, detail: string) {
    super(detail);
    this.name = "ApiError";
    this.status = status;
  }

  /** Whether this is "you are not signed in" rather than "you may not do that". */
  get isUnauthenticated(): boolean {
    return this.status === 401;
  }
}

/**
 * Turn a refusal into an `ApiError` carrying the backend's own `detail`.
 *
 * The detail is the message a moderator ends up reading — "no such pool: spma" beats
 * "400" — and it is written to be read, so it is shown rather than mapped to something
 * of our own. FastAPI's validation errors are the exception: their `detail` is a list of
 * objects, which is not a sentence, so those get a general one.
 */
const throwOnError: Middleware = {
  async onResponse({ response }) {
    if (response.ok) return response;

    let detail: unknown;
    try {
      detail = ((await response.clone().json()) as Problem).detail;
    } catch {
      detail = undefined;
    }
    throw new ApiError(
      response.status,
      typeof detail === "string" ? detail : `the backend answered ${response.status}`,
    );
  },
};

export const api = createClient<paths>({
  baseUrl: BASE_URL,
  credentials: "same-origin",
  // Looked up per call rather than captured. `createClient` would otherwise bind
  // whatever `fetch` was when this module loaded, which is before the tests install
  // theirs — and the symptom is a real network request to a port nobody is listening on
  // rather than an error saying the interceptor missed.
  fetch: (request) => globalThis.fetch(request),
});
api.use(throwOnError);

/**
 * The response body, or a thrown `ApiError`.
 *
 * `openapi-fetch` returns `{ data, error }` and our middleware throws instead, so `data`
 * is always present by the time this runs — but its type does not know that, and React
 * Query wants a value rather than a union.
 */
export function unwrap<T>(result: { data?: T }): T {
  return result.data as T;
}

export type Pool = components["schemas"]["PoolRead"];
export type Listing = components["schemas"]["ListingRead"];
export type ListingPage = components["schemas"]["ListingPage"];
export type BulkResult = components["schemas"]["BulkResult"];
export type Guild = components["schemas"]["GuildRead"];
export type Subscription = components["schemas"]["SubscriptionRead"];
export type SubscriptionLevel = components["schemas"]["SubscriptionLevel"];
export type GuildException = components["schemas"]["ExceptionRead"];
export type NotificationChannel = components["schemas"]["NotificationChannelRead"];
export type Outcome = components["schemas"]["EnforcementOutcomeRead"];
export type OutcomeStatus = components["schemas"]["OutcomeStatus"];
export type AuditEntry = components["schemas"]["AuditLogRead"];
export type SignedIn = components["schemas"]["SignedInRead"];
export type OpsOverview = components["schemas"]["OpsOverview"];
export type ActivityPoint = components["schemas"]["ActivityPoint"];
export type FailureGroup = components["schemas"]["FailureGroup"];
export type Job = components["schemas"]["JobRead"];
export type JobStatus = components["schemas"]["JobStatus"];
