/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Outside the token, because the compose healthcheck has no credentials.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Who the caller is, and the one thing the UI needs to know they can do.
         *
         *     `manages_pools` is a cached Discord lookup and `is_owner` is a set membership; both
         *     decide which navigation the SPA draws. They are conveniences, not gates: every route
         *     behind them resolves the same thing again for itself, so a stale `false` hides a link
         *     and a stale `true` produces a 403 rather than an escalation.
         *
         *     Service callers get an answer too, with no session attached. That is what the bot's
         *     contract test reads, and what makes "am I talking to a backend that knows me" one
         *     call rather than a guess.
         */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description End this session and clear the cookie.
         *
         *     A service caller has no session to end, and gets the same 204: logging out is
         *     idempotent, and there is nothing here worth telling a caller apart over.
         */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Pools
         * @description Every pool, by name.
         */
        get: operations["list_pools_pools_get"];
        put?: never;
        /**
         * Create Pool
         * @description Create a pool.
         */
        post: operations["create_pool_pools_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pools/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Pool
         * @description One pool.
         */
        get: operations["read_pool_pools__name__get"];
        put?: never;
        post?: never;
        /**
         * Delete Pool
         * @description Delete a pool, its listings and every subscription to it.
         *
         *     The enforcement outcomes it caused survive, holding no foreign key to it — which is
         *     what leaves `revert` able to find the bans afterwards.
         */
        delete: operations["delete_pool_pools__name__delete"];
        options?: never;
        head?: never;
        /**
         * Update Pool
         * @description Rename a pool, or change its description.
         *
         *     A rename rewrites nothing else: listings and subscriptions reference the surrogate
         *     key, which is why the key is there.
         */
        patch: operations["update_pool_pools__name__patch"];
        trace?: never;
    };
    "/pools/{name}/listings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Pool Listings
         * @description Everyone listed on one pool, a page at a time.
         *
         *     Paginated because `global` is not a list anybody scrolls: the migrated data has
         *     thousands of listings on it, and phase 4's `/list_pools` timeout is what happens when
         *     a route that was fine at ten rows meets production.
         *
         *     Ordered by id, which is also the page cursor. `created_at` is what a human reads but
         *     it is not unique, and a cursor that can repeat a value can skip a row.
         */
        get: operations["list_pool_listings_pools__name__listings_get"];
        put?: never;
        /**
         * Create Listing
         * @description List a user on a pool, and enqueue the enforcement that follows.
         */
        post: operations["create_listing_pools__name__listings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pools/{name}/listings/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Listings
         * @description List many users on a pool at once, and enqueue enforcement for each.
         *
         *     Web-only: no slash command sends this, because a text box in Discord is not where
         *     anybody should be pasting three hundred user IDs.
         *
         *     One job per new listing rather than one job for the batch. The worker's unit of work
         *     is a listing fanned out across subscribing guilds (phase 3), and a batch-shaped job
         *     would need its own retry and its own accounting against ADR 0007's breaker for no
         *     benefit — the queue is a table, and rows are cheap.
         *
         *     Users already listed are skipped and reported, not treated as failures. Duplicates
         *     within one request collapse the same way, so pasting a list with repeats in it does
         *     what the person meant.
         *
         *     One audit row per listing, exactly as if they had been added one at a time, because
         *     "why is this user listed and who did it" is the question the log exists to answer and
         *     a single summary row cannot. The rows carry `bulk: true` so a batch is still
         *     recognisable as one.
         */
        post: operations["create_listings_pools__name__listings_bulk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pools/{name}/listings/bulk-delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete Listings
         * @description Remove many listings from a pool at once.
         *
         *     A POST rather than a DELETE with a body: a request body on DELETE is permitted but
         *     not reliably carried, and the one operation where a proxy silently dropping the body
         *     would mean "delete nothing" is not the place to find out which proxies those are.
         *
         *     `revert` lifts the bans each removal leaves unjustified, and is off by default for
         *     the same reason it is everywhere else (ADR 0005).
         */
        post: operations["delete_listings_pools__name__listings_bulk_delete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/listings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List User Listings
         * @description Why this user is listed, across every pool.
         *
         *     This is the lookup ADR 0001 names as the first rule it expects to relax — today it
         *     needs membership of some guild Timothy is in, and the intent is a subscribing guild's
         *     own moderators. Changing that is a line in :mod:`timothy_api.policy`.
         */
        get: operations["list_user_listings_users__user_id__listings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pools/{name}/listings/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Listing
         * @description Remove a listing, optionally lifting the bans it was holding up.
         */
        delete: operations["delete_listing_pools__name__listings__user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/guilds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List My Guilds
         * @description Every guild Timothy is in that this caller administers.
         *
         *     The web UI's front door: a person signs in and has to be shown which of their servers
         *     they can configure, without being shown anybody else's. Filtering rather than gating
         *     is the whole design — there is no operation "administrator somewhere", so the list is
         *     built by asking Discord about each candidate.
         *
         *     What that costs depends on who is asking. A browser brings the guilds Discord said it
         *     was in at login (ADR 0010), so the candidates are that intersected with Timothy's —
         *     a handful, not the hundred-odd Timothy is in. A service caller has no snapshot and
         *     pays a resolved permission per guild, which is why the bot has no command for this.
         */
        get: operations["list_my_guilds_guilds_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/guilds/{guild_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Guild
         * @description One guild's state.
         */
        get: operations["read_guild_guilds__guild_id__get"];
        /**
         * Register Guild
         * @description Record that Timothy is in a guild.
         *
         *     Idempotent, because the bot re-announces its guilds every time the gateway
         *     reconnects. Only the first registration auto-subscribes; a guild that has since
         *     unsubscribed stays unsubscribed.
         */
        put: operations["register_guild_guilds__guild_id__put"];
        post?: never;
        /**
         * Deregister Guild
         * @description Forget a guild Timothy has left.
         *
         *     Its configuration cascades away with it. Its enforcement outcomes do not — they hold
         *     no foreign key, so a guild that re-adds Timothy still knows which of its bans were
         *     Timothy's.
         */
        delete: operations["deregister_guild_guilds__guild_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Guild
         * @description Pause or resume enforcement in one guild.
         *
         *     ADR 0007's per-guild rail: isolate one misbehaving guild without stopping the
         *     service. Resuming enqueues a catch-up, because everything that happened while paused
         *     deliberately recorded nothing.
         */
        patch: operations["update_guild_guilds__guild_id__patch"];
        trace?: never;
    };
    "/guilds/{guild_id}/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Subscriptions
         * @description What this guild has subscribed to.
         */
        get: operations["list_subscriptions_guilds__guild_id__subscriptions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/guilds/{guild_id}/subscriptions/{pool_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Subscription
         * @description Subscribe to a pool, or change the level of an existing subscription.
         *
         *     Enqueues enforcement when the level is new or has been raised. Lowering ban to warn
         *     enqueues nothing and lifts nothing — the guild asked to stop banning from now on, not
         *     to undo what it already did, and undoing it is what `revert` on the delete is for.
         */
        put: operations["set_subscription_guilds__guild_id__subscriptions__pool_name__put"];
        post?: never;
        /**
         * Delete Subscription
         * @description Unsubscribe, optionally lifting the bans this pool was holding up here.
         */
        delete: operations["delete_subscription_guilds__guild_id__subscriptions__pool_name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/guilds/{guild_id}/exceptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Exceptions
         * @description Everyone this guild has vouched for.
         */
        get: operations["list_exceptions_guilds__guild_id__exceptions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/guilds/{guild_id}/exceptions/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Create Exception
         * @description Vouch for a user in this guild.
         *
         *     Whether an exception lifts a ban Timothy has *already* issued was left open by phase
         *     2, and this is the answer: it does, but only when asked. That keeps every revert in
         *     the codebase the same shape — opt-in, defaulting off, and never touching a ban
         *     without a recorded outcome (ADR 0005). Creating an exception silently would make it
         *     the one action that unbans people as a side effect, and the flow a moderator actually
         *     has for "let this person back in" is the unban itself, which ADR 0006's hook already
         *     turns into an exception.
         */
        put: operations["create_exception_guilds__guild_id__exceptions__user_id__put"];
        post?: never;
        /**
         * Delete Exception
         * @description Withdraw the vouch, and let enforcement look at this user again.
         */
        delete: operations["delete_exception_guilds__guild_id__exceptions__user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/guilds/{guild_id}/notification-channel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Notification Channel
         * @description Where this guild's notifications go.
         */
        get: operations["read_notification_channel_guilds__guild_id__notification_channel_get"];
        /**
         * Set Notification Channel
         * @description Point this guild's notifications at a channel.
         */
        put: operations["set_notification_channel_guilds__guild_id__notification_channel_put"];
        post?: never;
        /**
         * Delete Notification Channel
         * @description Stop reporting to a channel.
         *
         *     Warn-level subscriptions with nowhere to report will record a failed outcome rather
         *     than a warned one, and so will be retried if a channel is set later.
         */
        delete: operations["delete_notification_channel_guilds__guild_id__notification_channel_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/guilds/{guild_id}/enforcement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Enforcement Outcomes
         * @description Every enforcement Timothy has recorded in this guild, newest first.
         */
        get: operations["list_enforcement_outcomes_guilds__guild_id__enforcement_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/member-join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Member Joined
         * @description A user joined a guild. Enforce against them there.
         *
         *     Queued rather than done inline. The work is the same as any other enforcement, and
         *     routing it through the queue is what gives it the retries and the circuit breaker.
         */
        post: operations["member_joined_events_member_join_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/ban-remove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ban Removed
         * @description A ban was lifted in a guild. Decide whether it should stick.
         *
         *     Whoever lifted it, any `banned` outcome for this user here has stopped being true and
         *     is cleared. Leaving it would have a later revert try to unban somebody who is already
         *     back, and would let the sweep believe this user is settled.
         */
        post: operations["ban_removed_events_ban_remove_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Audit Log
         * @description The most recent entries, newest first.
         */
        get: operations["read_audit_log_audit_log_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ops/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Overview
         * @description Everything a dashboard's top half needs, in one call.
         *
         *     One round trip rather than eight, because these are read together or not at all, and
         *     a screen that renders half its tiles is worse than one that renders none.
         *
         *     The settings come back with the counts on purpose. `dry_run` in particular decides
         *     what every other number on this page *means*: a zero in `outcomes.banned` reads as
         *     "nothing needed doing" when dry run is off and "nothing was issued" when it is on,
         *     and those are opposite situations.
         */
        get: operations["read_overview_ops_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ops/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Activity
         * @description What happened, per UTC day, per kind of thing.
         *
         *     Grouped in SQL rather than pulled into Python: a busy day is thousands of audit rows,
         *     and the window is up to ninety of them.
         *
         *     Days with nothing in them are absent rather than zero. A caller drawing a chart
         *     should fill the gaps itself — the API reporting zeroes it never observed would be
         *     inventing rows in an append-only record.
         */
        get: operations["read_activity_ops_activity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ops/failures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Failures
         * @description Enforcement that failed, by guild and by cause, worst first.
         *
         *     The everyday shape of this is one guild and one sentence repeated: a server that
         *     granted Timothy no ban permission fails identically for every listed user it has.
         *     Grouping turns four hundred rows into one line an operator can act on.
         *
         *     A `failed` outcome is not a failed job — it is a Discord call that retrying did not
         *     fix, which the sweep will try again when the world might have changed. Jobs are
         *     below, and are a different problem.
         */
        get: operations["read_failures_ops_failures_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ops/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Jobs
         * @description The queue itself, newest first.
         *
         *     Read-only, and there is deliberately no way to retry from here. A job reaches `failed`
         *     only after exhausting its attempts on something running it again would not fix — an
         *     unknown kind, a payload missing the key its handler needs. The failures that *are*
         *     worth retrying are recorded as enforcement outcomes instead, and the sweep picks
         *     those up on its own (see :mod:`timothy_api.enforcement.engine`). A retry button here
         *     would be a button that reliably does nothing.
         */
        get: operations["read_jobs_ops_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActivityPoint
         * @description How many of one kind of thing happened on one UTC day.
         *
         *     Read from `audit_log`, which is append-only, and *not* from `enforcement_outcomes`,
         *     which is one row per (guild, user, pool) updated in place — grouping that by
         *     `attempted_at` produces a plausible chart of the wrong thing.
         */
        ActivityPoint: {
            /** Day */
            day: string;
            /** Series */
            series: string;
            /** Count */
            count: number;
        };
        /**
         * AuditLogRead
         * @description One line of the append-only record.
         */
        AuditLogRead: {
            /** Id */
            id: number;
            /**
             * Actor
             * @example user:242024455190577152
             * @example system
             */
            actor: string;
            /** Action */
            action: string;
            /** Target */
            target: string | null;
            /** Detail */
            detail: {
                [key: string]: unknown;
            } | null;
            /**
             * At
             * Format: date-time
             */
            at: string;
        };
        /**
         * BulkListingCreate
         * @description Add many users to one pool in a single call.
         *
         *     Bounded, and not generously: a bulk listing is the operation that most deserves to be
         *     reviewed before it is sent, and every entry becomes enforcement across every
         *     subscribing guild. ADR 0007's circuit breaker will stop the fan-out long before this
         *     limit matters, which is the intended trade — see `ENFORCEMENT_BURST_LIMIT`.
         */
        BulkListingCreate: {
            /** Reason */
            reason: string;
            /** User Ids */
            user_ids: string[];
        };
        /**
         * BulkListingDelete
         * @description Remove many listings from one pool in a single call.
         */
        BulkListingDelete: {
            /** User Ids */
            user_ids: string[];
        };
        /**
         * BulkResult
         * @description What a bulk operation did, per user.
         *
         *     Partial success is reported rather than rolled back. A caller who asked for five
         *     hundred listings and gave three that were already there wants the four hundred and
         *     ninety-seven, and wants to be told about the three.
         */
        BulkResult: {
            /** Applied */
            applied: string[];
            /** Skipped */
            skipped: string[];
        };
        /**
         * EnforcementOutcomeRead
         * @description What Timothy did about one listing in one guild, and when.
         *
         *     Durable state rather than a log (ADR 0005): this is the record that makes a ban
         *     attributable to Timothy, and so the record that makes reverting it safe.
         */
        EnforcementOutcomeRead: {
            /** Guild Id */
            guild_id: string;
            /** User Id */
            user_id: string;
            /** Pool Id */
            pool_id: number;
            status: components["schemas"]["OutcomeStatus"];
            /** Reason */
            reason: string | null;
            /**
             * Attempted At
             * Format: date-time
             */
            attempted_at: string;
        };
        /**
         * EventAck
         * @description What the backend did with a relayed event.
         *
         *     Reported rather than silent so the bot can log it, and so an operator watching a
         *     manual unban can see whether the auto-exception fired or was suppressed.
         */
        EventAck: {
            /** Action */
            action: string;
        };
        /**
         * ExceptionCreate
         * @description Vouch for a user in a guild. Guild-wide, never scoped to one pool (ADR 0006).
         */
        ExceptionCreate: {
            /** Reason */
            reason?: string | null;
        };
        /**
         * ExceptionRead
         * @description A guild's declaration that a user is never to be banned by Timothy there.
         */
        ExceptionRead: {
            /** Guild Id */
            guild_id: string;
            /** User Id */
            user_id: string;
            /** Reason */
            reason: string | null;
            /**
             * Created By
             * @example user:242024455190577152
             * @example system
             */
            created_by: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * FailureGroup
         * @description Enforcement that failed, gathered by guild and by cause.
         *
         *     The shape the answer usually takes is "one guild, four hundred failures, all the same
         *     sentence" — a server that granted Timothy no ban permission. Grouping makes that one
         *     line instead of four hundred.
         */
        FailureGroup: {
            /** Guild Id */
            guild_id: string;
            /** Reason */
            reason: string | null;
            /** Count */
            count: number;
            /**
             * Latest At
             * Format: date-time
             */
            latest_at: string;
        };
        /**
         * GatewayEvent
         * @description Something that happened on the gateway, relayed by the bot.
         *
         *     The bot has no domain logic (PLAN.md) — it says what Discord told it and nothing
         *     about what should follow.
         */
        GatewayEvent: {
            /** Guild Id */
            guild_id: string;
            /** User Id */
            user_id: string;
        };
        /**
         * GuildRead
         * @description A guild Timothy is in.
         */
        GuildRead: {
            /** Guild Id */
            guild_id: string;
            /**
             * Joined At
             * Format: date-time
             */
            joined_at: string;
            /** Enforcement Paused */
            enforcement_paused: boolean;
        };
        /**
         * GuildUpdate
         * @description Pause or resume enforcement in one guild (ADR 0007's per-guild rail).
         */
        GuildUpdate: {
            /** Enforcement Paused */
            enforcement_paused: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Health
         * @description Liveness payload, used by the compose healthcheck.
         */
        Health: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        /**
         * InventoryCounts
         * @description How much of everything there is. One `COUNT(*)` each.
         */
        InventoryCounts: {
            /** Guilds */
            guilds: number;
            /** Guilds Paused */
            guilds_paused: number;
            /** Pools */
            pools: number;
            /** Listings */
            listings: number;
            /** Subscriptions */
            subscriptions: number;
            /** Exceptions */
            exceptions: number;
            /** Notification Channels */
            notification_channels: number;
        };
        /**
         * JobRead
         * @description One row of the queue, as an operator needs to read it.
         */
        JobRead: {
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /**
             * Run After
             * Format: date-time
             */
            run_after: string;
            /** Attempts */
            attempts: number;
            status: components["schemas"]["JobStatus"];
            /** Last Error */
            last_error: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * JobStatus
         * @description Where an enforcement job is in its life.
         * @enum {string}
         */
        JobStatus: "pending" | "running" | "done" | "failed";
        /**
         * ListingCreate
         * @description Add a user to a pool. An assertion, not an action — see CONTEXT.md.
         */
        ListingCreate: {
            /** User Id */
            user_id: string;
            /** Reason */
            reason: string;
        };
        /**
         * ListingPage
         * @description One page of listings, and how to ask for the next.
         *
         *     Keyset pagination, like the audit log: `after_id` is the last id on this page, and
         *     the table's ids only ever grow. An offset would shift under a reader every time
         *     somebody added a listing, which on a pool with thousands of them is every few
         *     seconds during a bulk import.
         */
        ListingPage: {
            /** Listings */
            listings: components["schemas"]["ListingRead"][];
            /** Next After Id */
            next_after_id: number | null;
            /** Total */
            total: number;
        };
        /**
         * ListingRead
         * @description A listing, carrying its pool's name so a caller need not join for it.
         */
        ListingRead: {
            /** Id */
            id: number;
            /** Pool Id */
            pool_id: number;
            /** Pool Name */
            pool_name: string;
            /** User Id */
            user_id: string;
            /** Reason */
            reason: string;
            /**
             * Created By
             * @example user:242024455190577152
             * @example system
             */
            created_by: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * NotificationChannelRead
         * @description Where Timothy reports what it did in a guild.
         */
        NotificationChannelRead: {
            /** Guild Id */
            guild_id: string;
            /** Channel Id */
            channel_id: string;
            /**
             * Created By
             * @example user:242024455190577152
             * @example system
             */
            created_by: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * NotificationChannelSet
         * @description Point a guild's notifications at a channel.
         */
        NotificationChannelSet: {
            /** Channel Id */
            channel_id: string;
        };
        /**
         * OpsOverview
         * @description One screen's worth of "is this thing working".
         *
         *     Deliberately includes the settings that decide what the numbers mean. `dry_run` in
         *     particular: every other figure here reads completely differently depending on it, and
         *     reading a zero as "nothing to do" when it is really "nothing was issued" is the
         *     mistake this exists to prevent.
         */
        OpsOverview: {
            /** Dry Run */
            dry_run: boolean;
            /** Workers Enabled */
            workers_enabled: boolean;
            /** Enforcement Burst Limit */
            enforcement_burst_limit: number;
            /** Sweep Interval Seconds */
            sweep_interval_seconds: number;
            /** Management Guild Id */
            management_guild_id: string | null;
            /** Login Configured */
            login_configured: boolean;
            counts: components["schemas"]["InventoryCounts"];
            queue: components["schemas"]["QueueDepth"];
            outcomes: components["schemas"]["OutcomeCounts"];
            /** Breaker Trips */
            breaker_trips: number;
            /** Last Activity At */
            last_activity_at: string | null;
        };
        /**
         * OutcomeCounts
         * @description Everything Timothy has recorded doing, by status, across every guild.
         */
        OutcomeCounts: {
            /** Banned */
            banned: number;
            /** Warned */
            warned: number;
            /** Failed */
            failed: number;
            /** Skipped Exception */
            skipped_exception: number;
        };
        /**
         * OutcomeStatus
         * @description The result of enforcing one listing in one guild.
         *
         *     A ``BANNED`` row is what makes a ban attributable to Timothy, and so what makes
         *     reverting it safe (ADR 0005). A ``WARNED`` row is simultaneously the audit trail and
         *     the dedupe key that keeps warnings to one per user, per pool, per guild.
         * @enum {string}
         */
        OutcomeStatus: "banned" | "warned" | "failed" | "skipped_exception";
        /**
         * PoolCreate
         * @description Create a pool.
         */
        PoolCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
        };
        /**
         * PoolRead
         * @description A pool as the API reports it.
         */
        PoolRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /**
             * Created By
             * @example user:242024455190577152
             * @example system
             */
            created_by: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * PoolUpdate
         * @description Rename a pool, or change its description, or both.
         *
         *     Renaming is web-only in the product (PLAN.md), but that is a decision about which
         *     slash commands exist, not about the API.
         */
        PoolUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
        };
        /**
         * QueueDepth
         * @description The state of the job table, which is the state of enforcement.
         *
         *     `sweep_outstanding` is the number of guilds with an `enforce_guild` job still to run.
         *     A round takes about two days against the migrated data (PLAN.md, "What a sweep
         *     costs"), so this counting down from the guild count is what "the sweep is working"
         *     looks like — and it staying flat is what a wedged worker looks like.
         */
        QueueDepth: {
            /** Pending */
            pending: number;
            /** Running */
            running: number;
            /** Done */
            done: number;
            /** Failed */
            failed: number;
            /** Sweep Outstanding */
            sweep_outstanding: number;
            /** Oldest Pending At */
            oldest_pending_at: string | null;
        };
        /**
         * SignedInRead
         * @description Who the caller is, as `/auth/me` reports it.
         *
         *     Everything but `actor` and `manages_pools` is `None` for a service caller, which has
         *     an actor but no session and so no name, face or expiry.
         */
        SignedInRead: {
            /**
             * Actor
             * @example user:242024455190577152
             * @example system
             */
            actor: string;
            /** User Id */
            user_id: string | null;
            /** Username */
            username: string | null;
            /** Avatar */
            avatar: string | null;
            /** Expires At */
            expires_at: string | null;
            /** Manages Pools */
            manages_pools: boolean;
            /** Is Owner */
            is_owner: boolean;
        };
        /**
         * SubscriptionLevel
         * @description How hard a guild has asked Timothy to enforce a pool.
         * @enum {string}
         */
        SubscriptionLevel: "ban" | "warn";
        /**
         * SubscriptionRead
         * @description A guild's decision to enforce a pool.
         */
        SubscriptionRead: {
            /** Guild Id */
            guild_id: string;
            /** Pool Id */
            pool_id: number;
            /** Pool Name */
            pool_name: string;
            level: components["schemas"]["SubscriptionLevel"];
            /**
             * Created By
             * @example user:242024455190577152
             * @example system
             */
            created_by: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * SubscriptionSet
         * @description Subscribe, or change the level of an existing subscription.
         */
        SubscriptionSet: {
            level: components["schemas"]["SubscriptionLevel"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                /** @description A browser session. */
                timothy_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignedInRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                /** @description A browser session. */
                timothy_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_pools_pools_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                /** @description A browser session. */
                timothy_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PoolRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_pool_pools_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                /** @description A browser session. */
                timothy_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PoolCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PoolRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_pool_pools__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: {
                /** @description A browser session. */
                timothy_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PoolRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_pool_pools__name__delete: {
        parameters: {
            query?: {
                /** @description Lift the bans this removal leaves unjustified. Off by default: reverting is only ever safe for bans Timothy has a recorded outcome for (ADR 0005). */
                revert?: boolean;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: {
                /** @description A browser session. */
                timothy_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_pool_pools__name__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: {
                /** @description A browser session. */
                timothy_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PoolUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PoolRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_pool_listings_pools__name__listings_get: {
        parameters: {
            query?: {
                /** @description How many listings to return. */
                limit?: number;
                /** @description Return listings after this id. Omit for the first page. */
                after_id?: number | null;
                /** @description Match against the reason, or against the user ID as text. */
                q?: string | null;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: {
                /** @description A browser session. */
                timothy_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_listing_pools__name__listings_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: {
                /** @description A browser session. */
                timothy_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ListingCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_listings_pools__name__listings_bulk_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: {
                /** @description A browser session. */
                timothy_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkListingCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_listings_pools__name__listings_bulk_delete_post: {
        parameters: {
            query?: {
                /** @description Lift the bans this removal leaves unjustified. Off by default: reverting is only ever safe for bans Timothy has a recorded outcome for (ADR 0005). */
                revert?: boolean;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: {
                /** @description A browser session. */
                timothy_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkListingDelete"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_user_listings_users__user_id__listings_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A Discord user ID. */
                user_id: string;
            };
            cookie?: {
                /** @description A browser session. */
                timothy_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_listing_pools__name__listings__user_id__delete: {
        parameters: {
            query?: {
                /** @description Lift the bans this removal leaves unjustified. Off by default: reverting is only ever safe for bans Timothy has a recorded outcome for (ADR 0005). */
                revert?: boolean;
            };
            header?: never;
            path: {
                name: string;
                /** @description A Discord user ID. */
                user_id: string;
            };
            cookie?: {
                /** @description A browser session. */
                timothy_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_my_guilds_guilds_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                /** @description A browser session. */
                timothy_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuildRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_guild_guilds__guild_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A Discord guild ID. */
                guild_id: string;
            };
            cookie?: {
                /** @description A browser session. */
                timothy_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuildRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_guild_guilds__guild_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A Discord guild ID. */
                guild_id: string;
            };
            cookie?: {
                /** @description A browser session. */
                timothy_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuildRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deregister_guild_guilds__guild_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A Discord guild ID. */
                guild_id: string;
            };
            cookie?: {
                /** @description A browser session. */
                timothy_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_guild_guilds__guild_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A Discord guild ID. */
                guild_id: string;
            };
            cookie?: {
                /** @description A browser session. */
                timothy_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GuildUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuildRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_subscriptions_guilds__guild_id__subscriptions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A Discord guild ID. */
                guild_id: string;
            };
            cookie?: {
                /** @description A browser session. */
                timothy_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_subscription_guilds__guild_id__subscriptions__pool_name__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A Discord guild ID. */
                guild_id: string;
                pool_name: string;
            };
            cookie?: {
                /** @description A browser session. */
                timothy_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubscriptionSet"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_subscription_guilds__guild_id__subscriptions__pool_name__delete: {
        parameters: {
            query?: {
                /** @description Lift the bans this unsubscribe leaves unjustified. Off by default: only bans with a recorded enforcement outcome are ever touched (ADR 0005). */
                revert?: boolean;
            };
            header?: never;
            path: {
                /** @description A Discord guild ID. */
                guild_id: string;
                pool_name: string;
            };
            cookie?: {
                /** @description A browser session. */
                timothy_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_exceptions_guilds__guild_id__exceptions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A Discord guild ID. */
                guild_id: string;
            };
            cookie?: {
                /** @description A browser session. */
                timothy_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExceptionRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_exception_guilds__guild_id__exceptions__user_id__put: {
        parameters: {
            query?: {
                /** @description Also lift the ban Timothy has already issued this user here, if it issued one. Off by default, like every other revert (ADR 0005): an exception is read as 'from now on', and only bans with a recorded outcome are touched. */
                revert?: boolean;
            };
            header?: never;
            path: {
                /** @description A Discord guild ID. */
                guild_id: string;
                /** @description A Discord user ID. */
                user_id: string;
            };
            cookie?: {
                /** @description A browser session. */
                timothy_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExceptionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExceptionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_exception_guilds__guild_id__exceptions__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A Discord guild ID. */
                guild_id: string;
                /** @description A Discord user ID. */
                user_id: string;
            };
            cookie?: {
                /** @description A browser session. */
                timothy_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_notification_channel_guilds__guild_id__notification_channel_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A Discord guild ID. */
                guild_id: string;
            };
            cookie?: {
                /** @description A browser session. */
                timothy_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationChannelRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_notification_channel_guilds__guild_id__notification_channel_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A Discord guild ID. */
                guild_id: string;
            };
            cookie?: {
                /** @description A browser session. */
                timothy_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificationChannelSet"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationChannelRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_notification_channel_guilds__guild_id__notification_channel_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A Discord guild ID. */
                guild_id: string;
            };
            cookie?: {
                /** @description A browser session. */
                timothy_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_enforcement_outcomes_guilds__guild_id__enforcement_get: {
        parameters: {
            query?: {
                /** @description Only outcomes with this status. `failed` is the interesting one. */
                status?: components["schemas"]["OutcomeStatus"] | null;
            };
            header?: never;
            path: {
                /** @description A Discord guild ID. */
                guild_id: string;
            };
            cookie?: {
                /** @description A browser session. */
                timothy_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnforcementOutcomeRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    member_joined_events_member_join_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                /** @description A browser session. */
                timothy_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GatewayEvent"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ban_removed_events_ban_remove_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                /** @description A browser session. */
                timothy_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GatewayEvent"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_audit_log_audit_log_get: {
        parameters: {
            query?: {
                /** @description How many entries to return. */
                limit?: number;
                /** @description Return entries older than this id. Omit for the newest page. */
                before_id?: number | null;
                /** @description Only entries with this exact action, e.g. `listing.create`. */
                action?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                /** @description A browser session. */
                timothy_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_overview_ops_overview_get: {
        parameters: {
            query?: {
                /** @description How many days back to count. UTC days. */
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                /** @description A browser session. */
                timothy_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpsOverview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_activity_ops_activity_get: {
        parameters: {
            query?: {
                /** @description How many days back to count. UTC days. */
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                /** @description A browser session. */
                timothy_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityPoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_failures_ops_failures_get: {
        parameters: {
            query?: {
                /** @description How many rows to return. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                /** @description A browser session. */
                timothy_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FailureGroup"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_jobs_ops_jobs_get: {
        parameters: {
            query?: {
                /** @description How many rows to return. */
                limit?: number;
                /** @description Return jobs older than this id. Omit for the newest page. */
                before_id?: number | null;
                /** @description Only jobs with this status. `failed` is the interesting one. */
                status?: components["schemas"]["JobStatus"] | null;
                /** @description Only jobs of this kind, e.g. `enforce_guild`. */
                kind?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                /** @description A browser session. */
                timothy_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
