"""The initial schema: PLAN.md's Schema section, whole.

Revision ID: 0001
Revises: nothing — this is the root.
Created: 2026-08-02 02:49:14.905886
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create every table."""
    # Autogenerated from timothy_core.db.models; reviewed by hand.
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("actor", sa.String(length=32), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("target", sa.String(length=128), nullable=True),
        sa.Column("detail", sa.JSON(), nullable=True),
        sa.Column("at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.create_index("ix_audit_log_at", ["at"], unique=False)

    op.create_table(
        "enforcement_outcomes",
        sa.Column(
            "guild_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "user_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("pool_id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "banned",
                "warned",
                "failed",
                "skipped_exception",
                name="outcome_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("attempted_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint(
            "guild_id", "user_id", "pool_id", name=op.f("pk_enforcement_outcomes")
        ),
    )
    op.create_table(
        "guilds",
        sa.Column(
            "guild_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("joined_at", sa.DateTime(), nullable=False),
        sa.Column("enforcement_paused", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("guild_id", name=op.f("pk_guilds")),
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("run_after", sa.DateTime(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "done",
                "failed",
                name="job_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index("ix_jobs_status_run_after", ["status", "run_after"], unique=False)

    op.create_table(
        "pools",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pools")),
        sa.UniqueConstraint("name", name=op.f("uq_pools_name")),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column(
            "user_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
    )
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.create_index("ix_sessions_expires_at", ["expires_at"], unique=False)

    op.create_table(
        "exceptions",
        sa.Column(
            "guild_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "user_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["guild_id"],
            ["guilds.guild_id"],
            name=op.f("fk_exceptions_guild_id_guilds"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("guild_id", "user_id", name=op.f("pk_exceptions")),
    )
    op.create_table(
        "listings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "user_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("pool_id", sa.Integer(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("created_by", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pool_id"],
            ["pools.id"],
            name=op.f("fk_listings_pool_id_pools"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_listings")),
        sa.UniqueConstraint("user_id", "pool_id", name=op.f("uq_listings_user_id_pool_id")),
    )
    with op.batch_alter_table("listings", schema=None) as batch_op:
        batch_op.create_index("ix_listings_user_id", ["user_id"], unique=False)

    op.create_table(
        "notification_channels",
        sa.Column(
            "guild_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "channel_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("created_by", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["guild_id"],
            ["guilds.guild_id"],
            name=op.f("fk_notification_channels_guild_id_guilds"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("guild_id", name=op.f("pk_notification_channels")),
    )
    op.create_table(
        "subscriptions",
        sa.Column(
            "guild_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("pool_id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column(
            "level",
            sa.Enum(
                "ban",
                "warn",
                name="subscription_level",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["guild_id"],
            ["guilds.guild_id"],
            name=op.f("fk_subscriptions_guild_id_guilds"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["pool_id"],
            ["pools.id"],
            name=op.f("fk_subscriptions_pool_id_pools"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("guild_id", "pool_id", name=op.f("pk_subscriptions")),
    )


def downgrade() -> None:
    """Drop every table, newest dependency first."""
    # Autogenerated from timothy_core.db.models; reviewed by hand.
    op.drop_table("subscriptions")
    op.drop_table("notification_channels")
    with op.batch_alter_table("listings", schema=None) as batch_op:
        batch_op.drop_index("ix_listings_user_id")

    op.drop_table("listings")
    op.drop_table("exceptions")
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.drop_index("ix_sessions_expires_at")

    op.drop_table("sessions")
    op.drop_table("pools")
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index("ix_jobs_status_run_after")

    op.drop_table("jobs")
    op.drop_table("guilds")
    op.drop_table("enforcement_outcomes")
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.drop_index("ix_audit_log_at")

    op.drop_table("audit_log")
